import './globals.css'
import './tailwind-globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/sansation" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        {/* <Header/> */}
        {children}
      </body>
    </html>
  )
}
